services:
  - type: web
    name: bigdata-project
    env: python
    buildCommand: |
      apt-get update && apt-get install -y default-jdk && pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port $PORT